"""update user table

Revision ID: b6f3444455d0
Revises: 2d610a9500d3
Create Date: 2022-07-18 22:29:46.922710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f3444455d0'
down_revision = '2d610a9500d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'location')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
